# Generated by Django 5.2.8 on 2025-11-21 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='capacidad',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registro',
            name='asistencia_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='certificado_generado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.registro')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inscritos', models.IntegerField()),
                ('total_asistentes', models.IntegerField()),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
            ],
        ),
    ]
